- COPYING
The FSF has issued a couple of tiny updates to the GPLv2. The main change is a new mailing address for the FSF headquarters.
This license text was taken verbatim from https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
> update FSF address in COPYING file

- testcases/kernel/fs/fsstress/fsstress.c
The semantics of the previous form of the condition did not make
sense, as should_stop was only respected when loops == 0. This
looks like a simple mistake with operator precedence.
> fsstress: Fix main loop condition

- testcases/kernel/containers/pidns/pidns01.c
pidns01.c: In function ?.hild_fn1?.
pidns01.c:62:21: warning: unused parameter ?.type?.[-Wunused-parameter]
int child_fn1(void *ttype)
^
pidns01.c: In function ?.ain?.
pidns01.c:98:2: warning: implicit declaration of function ?.ait?.[-Wimplicit-function-declaration]
pidns01.c:88:14: warning: unused parameter ?.rgc?.[-Wunused-parameter]
int main(int argc, char *argv[])
^
^
pidns01.c: In function ?.leanup?.
pidns01.c:113:13: warning: old-style function definition [-Wold-style-definition]
static void cleanup()
Signed-off-by: Yuan Sun <sunyuan3@huawei.com>
> Avoid the following warning when the ltp is built.

- runltplite.sh
Though it already runs subtest of tests with a
defined scenario file, it would be good to have
the skip tests options for the user for more flexibility
at run time.
> runltplite.sh: Adding SKIPFILE option

- runltplite.sh
The "-r" option has a argument. This bug is introduced by
PR #78 .
Signed-off-by: Wanlong Gao <wanlong.gao@gmail.com>
> runltplite: fix the "-r" option

- runltp
When we try to create hlml file on Dash it is failed. The runltp.sh try to save
the start time and the end time by `date.` But the value of `date` contains some
whitespaces and Dash split the value base on whitespace. So the assignment by
export fails. It looks Dash's bug but we can write 'export="${date}" as a manner.
Bash does not perform splitting on export, local and readonly so it works well on
Bash.
Signed-off-by: Jungsu Sohn <jsson98@gmail.com>
> runltp: Fix export assignment for Dash

- testcases/kernel/syscalls/brk/brk01.c
And  I use "%"PRIuPTR"" to replace "%ld" as Mike's advices.
> It is safer to use "uintptr_t" when we transfer "void *".

- testcases/kernel/syscalls/fsync/fsync01.c
What we need is a string pointer not an address of a string pointer
for calling "write(...)".
Signed-off-by: gyher <yahu.gao@intel.com>
> fsync/fsync01: Use the correct parameters while calling write

- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-1.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-2.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-3.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-4.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-5.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-6.c
Make sure to first initialize the variable before using it for
variable-length array initialization.
Signed-off-by: Ryan Zezeski <rpz@joyent.com>
> open_posix_testsuite: intialize var for VLA

- testcases/lib/test_net.sh
tst_ping should check number of input arguments before shift.
This bug cause a lot of testcases failed because of passing zero
argument when using tst_ping.
Signen-off-by: gidcs lks@gidcs.net
> testcases: fix bug in test_net.sh

- testcases/kernel/containers/netns/netns_helper.sh
When running netns tests with dash shell, the error message
'netns_comm.sh: 66: local: utility,: bad variable name' observed, and it
causes test failures. Refer to the below bug for more information about
the error with dash.
https://bugs.launchpad.net/ubuntu/+source/dash/+bug/139097
netns tests run with portable shell '/bin/sh'. Although local keyword is
supported by most of POSIX-compliant shells, it is not defined by POSIX.
And both 'cur_ipver' and 'spe_ipver' variables only used in
tst_check_iproute() in 'containers/netns/netns_helper.sh', scoping them
inside the function isn't needed. Removing the local keyword fixes the
above error and make the tests more portable.
Putting variable value in double quotes or splitting variable
declaration and assignment also works, but they are …
> containers/netns: remove local keyword for dash shell

- testcases/commands/mkfs/mkfs01.sh
The Dash shell doesn't handle the division in the substitution. The test can either be changed to use Bash or the division can be done before the substitution (e.g. `local rate=2`). Or, adding the `$` seems to work and it is the fewest character change.
Signed-off-by: Lucas Magasweran <lucas.magasweran@ieee.org>
> commands/mkfs: fix bashism in ntfs size computation

- testcases/kernel/device-drivers/tbio/tbio_user/tbio.c
- testcases/kernel/syscalls/getxattr/getxattr02.c
- testcases/kernel/syscalls/mknod/mknod01.c
- testcases/kernel/syscalls/mount/mount02.c
- testcases/kernel/syscalls/open/open11.c
- testcases/kernel/syscalls/setxattr/setxattr02.c
According to makedev(3), the makedev macro is defined in sys/sysmacros.h.
On later versions of glibc, this seems to now be enforced and the build
fails.  Once added the code compiles as usual.
> misc: Add sys/sysmacros.h header to includes when makedev is used.

- testcases/kernel/syscalls/clone/clone02.c
- testcases/kernel/syscalls/clone/clone05.c
CLONE_VM without CLONE_THREAD means that exit() from child process
will call all library destructors. As the VM is shared it means
that parent process will not be able to safely call any function
from library that depends on existence of its state.
Use _exit() instead of exit() in the child process to prevent library
destructors from being called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-test-project/ltp/208)
> syscalls/clone: handle CLONE_VM vs exit issue

- testcases/kernel/fs/iso9660/isofs.sh
The isofs.sh testcase was failing on Ubuntu, because it does not have
the mkisofs package installed by default.
Adding 'tst_check_cmds mkisofs' in the code can show that the package is
missing instead of throw an error.
Signed-off-by: Rodrigo R. Galvao <rosattig@linux.vnet.ibm.com>
> Fix small issue on isofs.sh testcase

- testcases/kernel/security/integrity/ima/tests/ima_measurements.sh
Signed-off-by: Xiao Liang <xiliang@redhat.com>
> ima/ima_measurements.sh: Fix a minor typo of '$($date)'

- testcases/network/stress/ipsec/ipsec_lib.sh
`tr` filters urandom by dropping non-hex symbols which results in
reducing entropy pool faster than needed.
Generate key with with one call to `hexdump` eliminating `head`.
`hexdump` is provided by `util-linux` packages, which also includes
such commands as `swapon`/`mkfs`/`fdisk`/`mount`, so it should be
already installed.
Signed-off-by: Dmitry Safonov <dima@arista.com>
> net/ipsec_lib.sh: Don't waste entropy from /dev/urandom

- testcases/open_posix_testsuite/conformance/interfaces/pthread_rwlock_timedrdlock/2-1.c
- testcases/open_posix_testsuite/conformance/interfaces/pthread_rwlock_timedrdlock/5-1.c
time_t value returns a 64 bit value, and therefore will overflow when casted to integer (year 2038 problem). In order to avoid integer overflow, the values should be stored to type time_t (signed 64 bit).
Signed-off-by: Keita Suzuki <keitasuzuki.park@sslab.ics.keio.ac.jp>
711d6c9
> Modify type to avoid overflows

- testcases/open_posix_testsuite/include/noatime.h
I accidentally omitted one of the arguments to a diagnostic printf I
added when I originally added the code. This addresses the issue by
adding the argument for the `path` parameter to the printf call to add
the diagnostics output I originally intended to add.
This does not affect Linux.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
> Fix `mounted_noatime` on *BSD

- testcases/open_posix_testsuite/include/affinity.h
errno.h is must be included in order to set errno and to obtain the
definition of ENOSYS.
This unbreaks compiling a part of the test suite on OSX and unbreaks it
on FreeBSD.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
> Fix compiling open_posix_testsuite on non-Linux platforms

- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-1.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-3.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-4.c
This commit is similar to 3373bb3, both in terms of logic and reasoning
for the change.
Reported by: clang and gcc with -Wunused
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
> Remove unused variables, `argc`/`argv`

- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-2.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-5.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-6.c
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
> Address more unused variables, `argc`/`argv`

- testcases/open_posix_testsuite/conformance/definitions/aio_h/4-1.c
- testcases/open_posix_testsuite/conformance/interfaces/lio_listio/14-1.c
- testcases/open_posix_testsuite/conformance/interfaces/mq_close/2-1.c
- testcases/open_posix_testsuite/conformance/interfaces/sigqueue/9-1.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-1.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-2.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-3.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-4.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-5.c
- testcases/open_posix_testsuite/functional/threads/pi_test/pitest-6.c
This PR does 2 things:
* Fixes a handful of one-off warnings that would prevent the compiler from building tests if `-Werror` was set in the CFLAGS file.
* Fixes some logic issues found by inspecting warning diagnostic output from the compiler.
Found with: clang
Tested with: CentOS 7.6.1810 (gcc 4.8.5); FreeBSD 13.0-CURRENT (clang 7.0.1)
> open_posix_testsuite: Fix -Werror issues (one-offs)

- testcases/network/stress/ns-tools/ns-igmp_querier.c
igmp querying may fail if there aren't enough input buffers or the output queue is full. Wait 1 second if `sendto(..)` fails with `ENOBUFS`, then try again.
Signed-off-by: supersojo <suyanjun218@163.com>
> network/stress: fix sending igmp query pkt too ofen cause test fail

- lib/tst_test.c
stderr was flushed in previous lines
and so flushing stdout
resolves: #716 
Signed-off-by: Vishwajith K <vishuvikas1996@yahoo.com>
> Fix typo in tst_test.c

- testcases/kernel/connectors/pec/README
'ilsten' to 'listen'
Signed-off-by: Tree Davies <tdavies@darkphysics.net>
> connectors/pec/README: Fix spelling error
